const $=s=>document.querySelector(s);let currentBrief=null;
$('#image').addEventListener('change',e=>{$('#fileName').textContent=e.target.files[0]?e.target.files[0].name:'＋ Upload hairstyle reference'});
$('#generate').addEventListener('click',async()=>{const preferences=$('#prefs').value.trim();if(!preferences){alert('Tell Aura what you want first.');return}const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences})});currentBrief=await r.json();renderBrief(currentBrief)});
$('#voice').addEventListener('click',()=>alert('Voice UI is reserved for the Snapdragon Distil-Whisper integration. The current demo keeps the prototype dependency-free.'));
$('#refresh').addEventListener('click',loadPassport);
function renderBrief(b){$('#engineBadge').textContent=b.engine;$('#brief').innerHTML=`<div class="brief-block"><b>REFERENCE</b><div>${esc(b.reference_description)}</div></div><div class="brief-block"><b>KEEP</b><ul>${b.keep.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="brief-block"><b>CHANGE</b><ul>${b.change.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="brief-block"><b>AVOID</b><ul>${b.avoid.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="brief-block"><b>MAINTENANCE</b><div>${esc(b.maintenance)}</div></div><div class="brief-block"><b>QUESTIONS FOR BARBER</b><ul>${b.questions_for_barber.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><button class="save" id="saveBrief">Save to Style Passport</button>`;$('#saveBrief').onclick=saveBrief}
async function saveBrief(){if(!currentBrief)return;await fetch('/api/passport',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brief:currentBrief})});await loadPassport();alert('Saved locally to your Style Passport.');}
async function loadPassport(){const r=await fetch('/api/passport');const d=await r.json();if(!d.styles.length){$('#passport').innerHTML='<div class="empty">No saved style yet.</div>';return}const s=d.styles[0];$('#passport').innerHTML=`<div class="style-row"><div class="pill"><b>Maintenance</b><span>${esc(s.maintenance)}</span></div><div class="pill"><b>Keep</b><span>${s.keep.map(esc).join(', ')}</span></div><div class="pill"><b>Avoid</b><span>${s.avoid.map(esc).join(', ')}</span></div></div>`}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}loadPassport();
